//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statuses
    {
        public Statuses()
        {
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int StatusID { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
    
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
